name: payment-spring-boot-starter test
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{github.ref_name}}
  cancel-in-progress: true #cancel previous runs when a new run is triggered

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
      - name: test via Maven
        run: |
          mvn test